PUT https://xtsh-plat.oss-cn-chengdu.aliyuncs.com/deepsea-plat%2Fdev%2Fpic%2F456.txt?Expires=1692956291&OSSAccessKeyId=STS.NU7kwHQDGiiPbfs4mKDFUgLyb&Signature=XuSaq7qVMhWdQQShBwPEct%2FVtbM%3D&security-token=CAIS6wF1q6Ft5B2yfSjIr5aCIM38vJtm3qu7YEDC0G0eSMl5iInSgDz2IHhMfXZhBuAZtP8znWpS7%2Fgclq9JQppiXlecmUzqZ14Oo22beIPkl5Gfz95t0e%2BIewW6Dxr8w7WhAYHQR8%2FcffGAck3NkjQJr5LxaTSlWS7OU%2FTL8%2BkFCO4aRQ6ldzFLKc5LLw950q8gOGDWKOymP2yB4AOSLjIx5FIg1DghuPjinZDHukWDtjCglL9J%2FbaWC4O%2FcsxhMK14V9qIx%2BFsfsLDqnUIs0EVpfgm0%2FYfpW6d5IjDXUM%2F%2BRyDNPHP4ib5%2FJKE5CxQGoABXu3rYQaHXlTqJH0zllItspXDAw%2FsHUxPINA%2BIARSJvXE8y3QOlk5fAN7riECuPn9YCJvh%2BFznBs0TezQohPruVFwcEEP0TCRjww9Lchh8V%2BIE%2F8zkbwrQnJRCgzgJtEKbGGgnlqG1bhrtgW6bUPzREMx9WDVNccmpR%2B5h7P%2FVa0gAA%3D%3D
Content-Type: text/plain; binary

--binary
Content-Disposition: attachment;filename="诗词歌赋.txt"

< /Users/tabuyos/Downloads/诗词歌赋.txt
--binary--

###
