// Code generated by tabuyos. DO NOT EDIT.

// Package service
// @author tabuyos
// @since 2023/09/15
// @description my_plat_resource
package service

import (
	"deepsea/helper"
	"deepsea/helper/database"
	"deepsea/helper/recorderx"
	"deepsea/helper/security"
	"deepsea/helper/snowflakeid"
	"deepsea/helper/validator"
	"deepsea/model/dto"
	"deepsea/model/entity"
	"deepsea/model/page"
	"deepsea/module/my/repository"
	"github.com/gin-gonic/gin"
	"time"
)

// iMyPlatResourceAutoGen 服务接口
type iMyPlatResourceAutoGen interface {
	validator.IValidator[*dto.MyPlatResource]
	Add(myPlatResource *dto.MyPlatResource) int64
	Remove(id int64) bool
	Modify(myPlatResource *dto.MyPlatResource) bool
	Find(id int64) *dto.MyPlatResource
	FindWithPage(query page.Query) *page.Result
}

// myPlatResourceAutoGen 服务接口
type myPlatResourceAutoGen struct {
	validator.AutoGenValidator[*dto.MyPlatResource]
	ctx *gin.Context
}

// Add 新增
func (svc *myPlatResourceAutoGen) Add(myPlatResource *dto.MyPlatResource) int64 {
	svc.ValidateAdd(myPlatResource)
	recorder := recorderx.FetchRecorder(svc.ctx)
	errorHandler := helper.ErrToLog(recorder)
	rty, release := repository.NewMyPlatResourceRty(svc.ctx)
	defer release()
	tx, err := database.FetchDB().Begin()
	errorHandler(err)
	defer helper.HandleTx(tx, errorHandler)

	now := time.Now()
	accountID := security.GetAccountID(svc.ctx)
	myPlatResource.ID = snowflakeid.GeneratePtr()
	myPlatResource.CreateAt = &now
	myPlatResource.CreateBy = &accountID
	myPlatResource.ModifyAt = &now
	myPlatResource.ModifyBy = &accountID
	newMyPlatResource := entity.NewMyPlatResource()
	myPlatResource.Into(newMyPlatResource)
	return rty.InsertNonNil(tx, newMyPlatResource)
}

// Remove 删除
func (svc *myPlatResourceAutoGen) Remove(id int64) bool {
	svc.ValidateRemove(id)
	recorder := recorderx.FetchRecorder(svc.ctx)
	recorder.Infof("删除 ID: %+v 的数据", id)
	errorHandler := helper.ErrToLog(recorder)
	rty, release := repository.NewMyPlatResourceRty(svc.ctx)
	defer release()
	tx, err := database.FetchDB().Begin()
	errorHandler(err)
	defer helper.HandleTx(tx, errorHandler)
	return rty.DeleteByID(tx, id)
}

// Modify 修改
func (svc *myPlatResourceAutoGen) Modify(myPlatResource *dto.MyPlatResource) bool {
	svc.ValidateModify(myPlatResource)
	recorder := recorderx.FetchRecorder(svc.ctx)
	recorder.Infof("修改 ID: %+v 的数据", *myPlatResource.ID)
	errorHandler := helper.ErrToLog(recorder)
	rty, release := repository.NewMyPlatResourceRty(svc.ctx)
	defer release()
	tx, err := database.FetchDB().Begin()
	errorHandler(err)
	defer helper.HandleTx(tx, errorHandler)
	now := time.Now()
	accountID := security.GetAccountID(svc.ctx)
	myPlatResource.ModifyAt = &now
	myPlatResource.ModifyBy = &accountID
	newMyPlatResource := entity.NewMyPlatResource()
	myPlatResource.Into(newMyPlatResource)
	return rty.UpdateNonNilByID(tx, newMyPlatResource)
}

// Find 根据 ID 查询详情
func (svc *myPlatResourceAutoGen) Find(id int64) *dto.MyPlatResource {
	svc.ValidateFind(id)
	recorder := recorderx.FetchRecorder(svc.ctx)
	recorder.Infof("查询 ID: %+v 的数据", id)
	rty, release := repository.NewMyPlatResourceRty(svc.ctx)
	defer release()
	myPlatResource := rty.SelectByID(id)
	if myPlatResource == nil {
		return nil
	}
	newMyPlatResource := dto.NewMyPlatResource()
	newMyPlatResource.From(myPlatResource)
	return newMyPlatResource
}

// FindWithPage 分页查询
func (svc *myPlatResourceAutoGen) FindWithPage(query page.Query) *page.Result {
	svc.ValidateFindWithPage(query)
	recorder := recorderx.FetchRecorder(svc.ctx)
	recorder.Infof("查询分页数据 page: %+v, size: %+v", query.Page, query.Size)
	rty, release := repository.NewMyPlatResourceRty(svc.ctx)
	defer release()
	myPlatResources, total := rty.SelectAllWithPage(query.Page, query.Size)
	if len(myPlatResources) == 0 {
		return nil
	}
	return page.NewResult(myPlatResources, total)
}
