// Code generated by tabuyos. DO NOT EDIT.

// Package dto
// @author tabuyos
// @since 2023/09/15
// @description my_plat_resource
package dto

import "deepsea/model/entity"

// MyPlatResource 自动生成
type MyPlatResource entity.MyPlatResource

// NewMyPlatResource 初始化
func NewMyPlatResource() *MyPlatResource {
	return &MyPlatResource{}
}

// From 读取 entity
func (rec *MyPlatResource) From(from *entity.MyPlatResource) {
	rec.ID = from.ID
	rec.Pid = from.Pid
	rec.PlatId = from.PlatId
	rec.Title = from.Title
	rec.Name = from.Name
	rec.Icon = from.Icon
	rec.Type = from.Type
	rec.Permission = from.Permission
	rec.Path = from.Path
	rec.Router = from.Router
	rec.Sort = from.Sort
	rec.CreateBy = from.CreateBy
	rec.CreateAt = from.CreateAt
	rec.ModifyBy = from.ModifyBy
	rec.ModifyAt = from.ModifyAt
	rec.Deleted = from.Deleted
}

// Into 写入 entity
func (rec *MyPlatResource) Into(into *entity.MyPlatResource) {
	into.ID = rec.ID
	into.Pid = rec.Pid
	into.PlatId = rec.PlatId
	into.Title = rec.Title
	into.Name = rec.Name
	into.Icon = rec.Icon
	into.Type = rec.Type
	into.Permission = rec.Permission
	into.Path = rec.Path
	into.Router = rec.Router
	into.Sort = rec.Sort
	into.CreateBy = rec.CreateBy
	into.CreateAt = rec.CreateAt
	into.ModifyBy = rec.ModifyBy
	into.ModifyAt = rec.ModifyAt
	into.Deleted = rec.Deleted
}
