// Code generated by tabuyos. DO NOT EDIT.

// Package dto
// @author tabuyos
// @since 2023/09/15
// @description my_plat_role
package dto

import "deepsea/model/entity"

// MyPlatRole 自动生成
type MyPlatRole entity.MyPlatRole

// NewMyPlatRole 初始化
func NewMyPlatRole() *MyPlatRole {
	return &MyPlatRole{}
}

// From 读取 entity
func (rec *MyPlatRole) From(from *entity.MyPlatRole) {
	rec.ID = from.ID
	rec.Pid = from.Pid
	rec.PlatId = from.PlatId
	rec.TenantId = from.TenantId
	rec.Name = from.Name
	rec.Status = from.Status
	rec.CreateBy = from.CreateBy
	rec.CreateAt = from.CreateAt
	rec.ModifyBy = from.ModifyBy
	rec.ModifyAt = from.ModifyAt
	rec.Deleted = from.Deleted
}

// Into 写入 entity
func (rec *MyPlatRole) Into(into *entity.MyPlatRole) {
	into.ID = rec.ID
	into.Pid = rec.Pid
	into.PlatId = rec.PlatId
	into.TenantId = rec.TenantId
	into.Name = rec.Name
	into.Status = rec.Status
	into.CreateBy = rec.CreateBy
	into.CreateAt = rec.CreateAt
	into.ModifyBy = rec.ModifyBy
	into.ModifyAt = rec.ModifyAt
	into.Deleted = rec.Deleted
}
