// Code generated by tabuyos. DO NOT EDIT.

// Package dto
// @author tabuyos
// @since 2023/09/15
// @description my_plat_authority_resource
package dto

import "deepsea/model/entity"

// MyPlatAuthorityResource 自动生成
type MyPlatAuthorityResource entity.MyPlatAuthorityResource

// NewMyPlatAuthorityResource 初始化
func NewMyPlatAuthorityResource() *MyPlatAuthorityResource {
	return &MyPlatAuthorityResource{}
}

// From 读取 entity
func (rec *MyPlatAuthorityResource) From(from *entity.MyPlatAuthorityResource) {
	rec.ID = from.ID
	rec.AuthorityId = from.AuthorityId
	rec.ResourceId = from.ResourceId
	rec.PlatId = from.PlatId
	rec.TenantId = from.TenantId
	rec.CreateBy = from.CreateBy
	rec.CreateAt = from.CreateAt
	rec.ModifyBy = from.ModifyBy
	rec.ModifyAt = from.ModifyAt
	rec.Deleted = from.Deleted
}

// Into 写入 entity
func (rec *MyPlatAuthorityResource) Into(into *entity.MyPlatAuthorityResource) {
	into.ID = rec.ID
	into.AuthorityId = rec.AuthorityId
	into.ResourceId = rec.ResourceId
	into.PlatId = rec.PlatId
	into.TenantId = rec.TenantId
	into.CreateBy = rec.CreateBy
	into.CreateAt = rec.CreateAt
	into.ModifyBy = rec.ModifyBy
	into.ModifyAt = rec.ModifyAt
	into.Deleted = rec.Deleted
}
