// Code generated by tabuyos. DO NOT EDIT.

// Package dto
// @author tabuyos
// @since 2023/09/15
// @description my_plat_authority
package dto

import "deepsea/model/entity"

// MyPlatAuthority 自动生成
type MyPlatAuthority entity.MyPlatAuthority

// NewMyPlatAuthority 初始化
func NewMyPlatAuthority() *MyPlatAuthority {
	return &MyPlatAuthority{}
}

// From 读取 entity
func (rec *MyPlatAuthority) From(from *entity.MyPlatAuthority) {
	rec.ID = from.ID
	rec.TenantId = from.TenantId
	rec.PlatId = from.PlatId
	rec.Name = from.Name
	rec.Status = from.Status
	rec.CreateBy = from.CreateBy
	rec.CreateAt = from.CreateAt
	rec.ModifyBy = from.ModifyBy
	rec.ModifyAt = from.ModifyAt
	rec.Deleted = from.Deleted
}

// Into 写入 entity
func (rec *MyPlatAuthority) Into(into *entity.MyPlatAuthority) {
	into.ID = rec.ID
	into.TenantId = rec.TenantId
	into.PlatId = rec.PlatId
	into.Name = rec.Name
	into.Status = rec.Status
	into.CreateBy = rec.CreateBy
	into.CreateAt = rec.CreateAt
	into.ModifyBy = rec.ModifyBy
	into.ModifyAt = rec.ModifyAt
	into.Deleted = rec.Deleted
}
