// Code generated by tabuyos. DO NOT EDIT.

// Package api
// @author tabuyos
// @since 2023/09/15
// @description my_plat_role
package api

import (
	"deepsea/helper/recorderx"
	"deepsea/model/dto"
	"deepsea/model/page"
	"deepsea/model/reply"
	"deepsea/module/my/service"
	"github.com/gin-gonic/gin"
	"net/http"
	"strconv"
)

// MyPlatRoleHandler API 处理器
type MyPlatRoleHandler struct{}

// NewMyPlatRoleHandler 创建 API 处理器
func NewMyPlatRoleHandler() *MyPlatRoleHandler {
	return &MyPlatRoleHandler{}
}

// Add 新增数据
// @Summary      新增数据
// @Description  新增数据
// @Tags         my,MyPlatRole
// @Accept       json
// @Produce      json
// @Param        req_info    body     dto.MyPlatRole  true  "待新增的数据对象"
// @Success      200  {object}  reply.Reply  "操作结果"
// @Security     ApiKeyAuth
// @Router       /my/role/add [put]
func (*MyPlatRoleHandler) Add() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		recorder := recorderx.FetchRecorder(ctx)
		newMyPlatRole := dto.NewMyPlatRole()
		err := ctx.ShouldBindJSON(newMyPlatRole)
		recorder.MaybePanic(err)
		svc, release := service.NewMyPlatRoleSvc(ctx)
		defer release()
		id := svc.Add(newMyPlatRole)
		if id != 0 {
			ctx.JSON(http.StatusOK, reply.OkPayload(id))
		} else {
			ctx.JSON(http.StatusOK, reply.FailedMessage("新增失败"))
		}
	}
}

// Remove 根据 ID 删除数据
// @Summary      删除数据
// @Description  根据 ID 删除数据
// @Tags         my,MyPlatRole
// @Accept       json
// @Produce      json
// @Param        id    query     integer  true  "待删除 ID"
// @Success      200  {object}  reply.Reply  "操作结果"
// @Security     ApiKeyAuth
// @Router       /my/role/remove [delete]
func (*MyPlatRoleHandler) Remove() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		recorder := recorderx.FetchRecorder(ctx)
		id, err := strconv.ParseInt(ctx.Query("id"), 10, 64)
		recorder.MaybePanic(err)
		if id <= 0 {
			ctx.JSON(http.StatusOK, reply.FailedMessage("请传递正确的 ID"))
			return
		}
		svc, release := service.NewMyPlatRoleSvc(ctx)
		defer release()
		op := svc.Remove(id)
		if op {
			ctx.JSON(http.StatusOK, reply.Ok().WithState(op).WithMessage("操作成功"))
			return
		}
		ctx.JSON(http.StatusOK, reply.Failed().WithState(op).WithMessage("操作失败"))
	}
}

// Modify 根据 ID 修改数据
// @Summary      修改数据
// @Description  根据 ID 修改数据
// @Tags         my,MyPlatRole
// @Accept       json
// @Produce      json
// @Param        req_info    body     dto.MyPlatRole  true  "待修改的数据对象"
// @Success      200  {object}  reply.Reply  "操作结果"
// @Security     ApiKeyAuth
// @Router       /my/role/base-modify [post]
func (*MyPlatRoleHandler) Modify() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		recorder := recorderx.FetchRecorder(ctx)
		newMyPlatRole := dto.NewMyPlatRole()
		err := ctx.ShouldBindJSON(newMyPlatRole)
		recorder.MaybePanic(err)
		if newMyPlatRole.ID == nil {
			ctx.JSON(http.StatusOK, reply.FailedMessage("请传递正确的 ID, 以及需要修改的信息"))
			return
		}
		svc, release := service.NewMyPlatRoleSvc(ctx)
		defer release()
		op := svc.Modify(newMyPlatRole)
		if op {
			ctx.JSON(http.StatusOK, reply.OkMessage("操作成功"))
			return
		}
		ctx.JSON(http.StatusOK, reply.FailedMessage("操作失败"))
	}
}

// Detail 根据 ID 获取详情
// @Summary      获取详情
// @Description  根据 ID 获取详情
// @Tags         my,MyPlatRole
// @Accept       json
// @Produce      json
// @Param        id    query     integer  true  "查询 ID"
// @Success      200  {object}  reply.Reply{payload=dto.MyPlatRole}  "查询详情"
// @Security     ApiKeyAuth
// @Router       /my/role/detail [get]
func (*MyPlatRoleHandler) Detail() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		recorder := recorderx.FetchRecorder(ctx)
		id, err := strconv.ParseInt(ctx.Query("id"), 10, 64)
		recorder.MaybePanic(err)
		if id <= 0 {
			ctx.JSON(http.StatusOK, reply.FailedMessage("请传递正确的 ID"))
			return
		}
		svc, release := service.NewMyPlatRoleSvc(ctx)
		defer release()
		myPlatRole := svc.Find(id)
		if myPlatRole != nil {
			ctx.JSON(http.StatusOK, reply.OkPayload(myPlatRole))
			return
		}
		ctx.JSON(http.StatusOK, reply.Failed().WithMessage("无对应数据"))
	}
}

// ListPage 分页列表
// @Summary      分页列表
// @Description  获取分页列表
// @Tags         my,MyPlatRole
// @Accept       json
// @Produce      json
// @Param        req_info    body     page.Query  false  "分页信息"
// @Success      200  {object}  reply.Reply{payload=[]page.Result}  "分页列表"
// @Security     ApiKeyAuth
// @Router       /my/role/list-page [post]
func (*MyPlatRoleHandler) ListPage() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		recorder := recorderx.FetchRecorder(ctx)
		query := page.NewQuery()
		query.Page = 1
		query.Size = 20
		err := ctx.ShouldBindJSON(query)
		recorder.MaybePanic(err)
		svc, release := service.NewMyPlatRoleSvc(ctx)
		defer release()
		ctx.JSON(http.StatusOK, reply.OkPayload(svc.FindWithPage(*query)))
	}
}
